### PR TITLE
orca - reuse protocol "connect" for a generic identity only flow

### PR DESCRIPTION
**Pull request by OrlandoLee**
creating a generic identity only flow in sybil so Orca team and other team can reuse it. 

**Background**: Orca team is trying to find a way to link identity(twitter) to a wallet address but we don't need sybil to do delegation and proposal. So having a generic flow that allows user to just link their identity to wallet address is useful.

**Implementation**:  treat "connect" as a special protocol so that twitter redirect url continue works after user finishes the link identity flow.

**Note**: the UI is not polished, creating a PR to get an initial review so that I know whether this solution is on the right track or not.
ezgif com-gif-maker

### CODE REVIEW

**Comment by callil** [comment]
@OrlandoLee Nice start - I do think the experience should occur either in the main UI with sidebars or as a modal above it. Will run locally and take a look.

**Comment by OrlandoLee** [comment]
@callil thanks! I will add an icon to the sidebar and add sidebar to the flow. Anything else you see that needs to be changed at this moment?

**Comment by OrlandoLee** [comment]
Screen Shot 2021-12-07 at 10 10 59 AM
Screen Shot 2021-12-07 at 10 10 46 AM
These are the screenshots for the new UI. Let me know what you think. (logo needs to be updated)
@callil

**Comment by callil** [comment]
Just made some small tweaks! Looking good to me :)

**Comment by OrlandoLee** [comment]
@callil thanks for these fixes! Wondering what's the process for merging this into master? If things look good could you merge this in so that I can test it end to end with twitter integration (since the callback url is https://sybil.org/)

**Comment by callil** [comment]
Let's get this merged!

**Pull request merged**
