### PR TITLE
Integrating Aave into Sybil

### PR DESCRIPTION
**Pull request by PengFei-Ethereum**
I am working on integrating Aave into the Sybil site, when testing in my local environment it seems that adding an extra protocol messes with the design of the pull down bar when selecting a protocol.

image-1

The image above shows that when you select Aave it will hide the Uniswap protocol. Would appreciate any feedback on how to fix this issue?

### CODE REVIEW

**Comment by ianlapham** [comment]
@PengFei-Ethereum Thanks for starting this! I can take a look at the dropdown issue here

**Comment by PengFei-Ethereum** [comment]
> @PengFei-Ethereum Thanks for starting this! I can take a look at the dropdown issue here

Ian, I also have an issue understanding how the graph works, for example I see that Aave has a governance v2 graph available, but it doesn't seem like it includes everything you guys would need to incorporate into the Sybil site. I'm not experienced with subgraphs, but would you happen to know someone willing to take a look and help getting it integrated?
This is the most recent subgraph for Aave governance I could find: https://thegraph.com/explorer/subgraph/aave/governance-v2

**Comment by Ulydev** [comment]
Hi, @PengFei-Ethereum, I submitted a PR to your fork that fixes the dropdown layout issue. Once that's merged in your fork we can try to merge it here.

**Comment by PengFei-Ethereum** [comment]
> Hi, @PengFei-Ethereum, I submitted a PR to your fork that fixes the dropdown layout issue. Once that's merged in your fork we can try to merge it here.

Can confirm that the merge request successfully fixes the dropdown menu issue.

**Comment by Ulydev** [comment]
Hi @ianlapham , any update? Is there any way I can help?

**Comment by ianlapham** [comment]
> Hi @ianlapham , any update? Is there any way I can help?

@Ulydev Seems like the dropdown is working now, however it looks like the Aave subgraph is not matching the schema correctly. This isn't a direct fork of compound or uniswap governance is it?

I'm noticing some errors when running some of the queries on the Aave subgraph. '''Error: GraphQL error: Type `Query` has no field `delegates`'''

If its not this will require more work of adding some abstraction layer on top of the data.

**Comment by Ulydev** [comment]
@ianlapham Thanks for your quick reply. Will investigate.

**Comment by ianlapham** [comment]
> @ianlapham Thanks for your quick reply. Will investigate.

Cool I'll be taking a look soon on what it will take - would love to get more protocols integrated including Aave

**Review by Abeseba — APPROVED** [review]

**Comment by PengFei-Ethereum** [comment]
I believe we can close this pull request as Aave is now integrated into Sybil.

**Pull request closed without merging**
