### PR TITLE
feat(governance): add yearn.finance

### PR DESCRIPTION
**Pull request by developerfred**
- **Governance Contract:** [0xBa37B002AbaFDd8E89a1995dA52740bbC013D992](https://etherscan.io/address/0xBa37B002AbaFDd8E89a1995dA52740bbC013D992)

- **Token Contract:** [0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e](https://etherscan.io/address/0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e)
- **SubGraph Announcement:**** [subgraph](https://gov.yearn.finance/t/yearn-governance-subgraph-for-querying-data-on-the-front-end-created/2356)

### CODE REVIEW

**Comment by ianlapham** [comment]
@developerfred Awesome work getting this started - im noticing some issues with request on the yearn subgraph. Is this subgraph public? Happy to help debug but cant see the source.

**Comment by ianlapham** [comment]
@developerfred Actually it looks like this subgraph has a slightly different schema - if Yearn is an exact fork of Compound it may be better to deploy the same subgraph that tracks Compound and Uniswap governance with the Yearn addresses switched in

**Comment by developerfred** [comment]
> @developerfred Actually it looks like this subgraph has a slightly different schema - if Yearn is an exact fork of Compound it may be better to deploy the same subgraph that tracks Compound and Uniswap governance with the Yearn addresses switched in

@ianlapham  Perfect, I will deploy a fork of the subgraph of the compound to the yearn.finance

**Comment by ianlapham** [comment]
@developerfred I accidently included this history into my latest commit - would you mind making another PR? Sorry about that. One issue im noticing with yearn is that its not a direct fork of compound - so im not sure if the subgraph will work correctly if deployed with the yearn addresses. 

There may be a way where we can add an asbtarction layer on top of the data fetching to support different gov types like yearn

**Comment by developerfred** [comment]
> @developerfred I accidently included this history into my latest commit - would you mind making another PR? Sorry about that. One issue im noticing with yearn is that its not a direct fork of compound - so im not sure if the subgraph will work correctly if deployed with the yearn addresses.
> 
> There may be a way where we can add an asbtarction layer on top of the data fetching to support different gov types like yearn

No worries, yes I have to think about the best way to do this, there are many protocols that are fork of the yearn.  Creating this new way of analyzing a governance that can cover 80% of DeFi

**Comment by PengFei-Ethereum** [comment]
> @developerfred I accidently included this history into my latest commit - would you mind making another PR? Sorry about that. One issue im noticing with yearn is that its not a direct fork of compound - so im not sure if the subgraph will work correctly if deployed with the yearn addresses.
> 
> There may be a way where we can add an asbtarction layer on top of the data fetching to support different gov types like yearn

Aave is in a similar situation where the subgraph isn't a direct fork of Compound, and there are key differences with Aave and Compound. I've spoken with a member of the Aave team and they seem to be working on a subgraph for Sybil, but if there is a way to add an abstraction layer on top of the data fetching currently in production, that would help projects like Aave and Yearn maintain their subgraphs and still being able to be implemented into Sybil.

**Pull request merged**
